[program:follow_bot]
directory=/usr/python_robot/follow_bot/src
command=/usr/python_robot/follow_bot/venv/bin/python main.py
user=root
autostart=true
autorestart=true
redirect_stderr=true
# stdout_logfile=/usr/python_robot/follow_bot/logs/tgbot.log
startsecs = 0